### ISSUE TITLE
Starting marker 404 error on Forge hosting

### ISSUE THREAD

**Issue by benjosity** [kandashi/Next-Up#88]
Seems as though the string formatting for the start marker isn't being formatted with Forge hosting taken into account causing a 404 error. Turn marker is working fine with the same URL format specified.

Turn Marker - https://assets.forge-vtt.com/bazaar/modules/jb2a_patreon-2d960ceba80cc778/assets/Library/Generic/Magic_Signs/Conjuration_01_Yellow_Circle_800x800.webm

Start-Turn Marker - https://assets.forge-vtt.com/bazaar/modules/Next-Up/assets/Markers/start.png

<img width="1196" alt="Screenshot 2021-06-04 at 16 36 33" src="https://user-images.githubusercontent.com/5020948/120828269-3ca05f80-c554-11eb-9fe4-bc78d195a1c2.png">

**Comment by kakaroto** [comment]
It looks like you entered `/assets.forge-vtt.com/bazaar/modules/Next-Up/assets/Markers/start.png` as the url for the marker, instead of `https://assets.forge-vtt.com/bazaar/modules/Next-Up/assets/Markers/start.png`. 
I was told it works fine when using the url with the `https://` protocol included.
Can you confirm ?

**Comment by kandashi** [comment]
ahh, this is likely on the 0.7.6 branch where had to do some finicky stix to make a file picker work. The 0.8.6 branch should work fine here

**Comment by Th3Rom3** [comment]
I can replicate the problem on a local node.js installation.
Turn marker icon seems fine but the path to the start-turn marker seems to be constructed in a weird way. It always seems to cut  of the first six characters of the relative path. If I manually change the relative path from 

`modules/Next-Up/Markers/BlackCross.png`
to
`123456/modules/Next-Up/Markers/BlackCross.png`

It works and the path is constructed correctly.
I sadly cannot provide more sophisticated input atm since I would have to look more into js syntax. If I can provide additional info let me know.

**Comment by Th3Rom3** [comment]
I would speculate that this might be the same problem with the forge hosting since the URL in kakaroto's post is also missing the first seven characters.

**Comment by kandashi** [comment]
Yes, this is a result of how the 0.7.6 version works I'm afraid

**Comment by Th3Rom3** [comment]
I should have clarified,  I am running Foundry 8.6. on node.js 14.17.

My bad.

**Comment by kandashi** [comment]
If you are on 0.8.6 make sure you are using the new version 0.1.01 as this works fine on the forge system

**Comment by kandashi** [comment]
I now see what the issue is, will fix now
